---
- hosts: 127.0.0.1
  user: dk
  gather_facts: no
  connection: local

  tasks:
    #Call ansible module "userinfo" with parameter "username=testuser"
    - name: 'Calling test_module'
      test_module: name="Hello World!"

    - name: 'Calling success via test_module'
      test_module: name="success is yes" success=yes

    - name: 'Calling fail via test_module'
      test_module: name="success is no" success=no